image: node:latest

stages:
  - test

# Cache modules in between jobs
cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/

before_script:
  - npm ci
  - echo merge request $CI_MERGE_REQUEST_TARGET_BRANCH_NAME

chromatic_publish_auto_accept_changes:
  stage: test
  script:
    - npm run build
    - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --auto-accept-changes
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  tags:
    - amd
    - docker
    - general
    - sellsuki
    - production

chromatic_publish:
  stage: test
  script:
    - npm run build
    - npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
  rules: 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
      allow_failure: false
  tags:
    - amd
    - docker
    - general
    - sellsuki
    - staging
