/**
 * Custom Elements Manifest (CEM) — analyzer config.
 *
 * Emits `dist/custom-elements.json` describing every <ssk-*> element's
 * attributes, properties, slots, events, CSS parts, and CSS custom
 * properties. Consumed by:
 *
 *   1. `ds3-mcp` server — replaces its hand-maintained component catalog
 *      (DES-2039 Layer 2, DES-2040, DES-2042, DES-2046, DES-2041 all read
 *      from this single source of truth).
 *   2. Storybook 8 autodocs — automatic API tables per story (future).
 *   3. VS Code Custom Elements VS Code plugin — type-aware HTML hints.
 *
 * Spec: https://github.com/webcomponents/custom-elements-manifest
 */

export default {
  // Source globs — every component class lives somewhere under src/.
  globs: ["src/**/*.ts"],

  // Skip generated, test, and demo files.
  exclude: [
    "src/__tests__/**",
    "src/**/*.test.ts",
    "src/**/*.stories.ts",
    "src/elements/icon/icon-data.ts", // generated; massive enum dump
    "src/elements/icon/country-icon.ts", // generated by scripts/generate-country
  ],

  outdir: "dist",

  // Lit-specific decorators (@property, @state, @query, @consume, @provide).
  litelement: true,

  // We're a published library — no need to walk dependency packages.
  dependencies: false,

  // Embed package.json metadata (name/version) so downstream consumers
  // know which release this manifest belongs to.
  packagejson: true,

  // Surface unhandled errors instead of silently producing empty modules.
  fast: false,
};
