// DES-2048 — generate dist/react-types.d.ts so React consumers no longer have
// to hand-roll JSX.IntrinsicElements for every ssk-* tag.
//
// Run automatically as part of `npm run build`. Source of truth: any
// `customElements.define("ssk-foo", ...)` call in src/.

import { glob } from "glob";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..", "..");
const SRC = path.join(ROOT, "src");
const OUT = path.join(ROOT, "dist", "react-types.d.ts");

const TAG_RE = /customElements\.define\(\s*["']ssk-([a-z0-9-]+)["']/g;

const tags = new Set();
const files = await glob("**/*.ts", { cwd: SRC, absolute: true });
for (const file of files) {
  const content = readFileSync(file, "utf8");
  let m;
  while ((m = TAG_RE.exec(content)) !== null) {
    tags.add(`ssk-${m[1]}`);
  }
}

const sorted = [...tags].sort();

const lines = [
  "// Auto-generated by scripts/generate-react-types. Do not edit by hand.",
  "// Regenerate with: npm run generate:react-types",
  "//",
  "// Usage in a React/TSX consumer project, either:",
  "//   1. add `\"@uxuissk/design-system-core/react-types\"` to tsconfig.json `types`",
  "//   2. or add `/// <reference types=\"@uxuissk/design-system-core/react-types\" />`",
  "//      at the top of any .tsx file.",
  "//",
  "// Note on prop typing: each tag accepts the standard React HTMLAttributes plus",
  "// arbitrary string-valued attributes (via `Record<string, unknown>`). This",
  "// matches how custom elements actually consume attributes in the DOM. For full",
  "// reactive prop typing per component, wrap with `@lit-labs/react` createComponent.",
  'import type * as React from "react";',
  "",
  "type SskJSXProps =",
  "  React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement> &",
  "  Record<string, unknown>;",
  "",
  'declare module "react" {',
  "  namespace JSX {",
  "    interface IntrinsicElements {",
  ...sorted.map((tag) => `      "${tag}": SskJSXProps;`),
  "    }",
  "  }",
  "}",
  "",
];

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, lines.join("\n"), "utf8");
console.log(`✓ Wrote ${path.relative(ROOT, OUT)} (${sorted.length} ssk-* tags)`);
